# Generated by Django 5.2.7 on 2025-10-14 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="视频标题")),
                (
                    "upload_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                ("video_url", models.URLField(max_length=216, verbose_name="视频URL")),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="封面图片URL",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="访问量")),
            ],
            options={
                "verbose_name": "视频",
                "verbose_name_plural": "视频",
                "ordering": ["-upload_time"],
            },
        ),
    ]
